import { defineType, defineField } from 'sanity'
import { TagIcon } from '@sanity/icons'
import { ComputedCostInput } from '../components/ComputedCostInput'

export const plan = defineType({
  name: 'plan',
  title: 'Plan',
  type: 'document',
  icon: TagIcon,
  groups: [
    { name: 'identity',   title: 'Identity' },
    { name: 'rules',      title: 'Rules & Limits' },
    { name: 'pricing',    title: 'Pricing' },
    { name: 'meta',       title: 'Meta' },
  ],
  fields: [
    defineField({
      name: 'firm',
      title: 'Firm',
      type: 'reference',
      to: [{ type: 'firm' }],
      group: 'identity',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'planId',
      title: 'Plan ID',
      type: 'slug',
      description: 'Unique machine ID e.g. apex-trader-funding-25000-eod',
      group: 'identity',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'planLabel',
      title: 'Plan Label',
      type: 'string',
      description: 'Display name e.g. EOD Trail 25K',
      group: 'identity',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'accountSize',
      title: 'Account Size ($)',
      type: 'number',
      group: 'identity',
      validation: (r) => r.required().positive(),
    }),
    defineField({
      name: 'accountType',
      title: 'Account Type',
      type: 'string',
      description: 'e.g. EOD Trail, Evaluation, Instant, Zero, Premium',
      group: 'identity',
    }),
    defineField({
      name: 'isOneTime',
      title: 'One-Time Fee (Instant/No Eval)',
      type: 'boolean',
      group: 'identity',
      initialValue: false,
    }),
    defineField({
      name: 'drawdownType',
      title: 'Drawdown Type',
      type: 'string',
      group: 'rules',
      options: {
        list: [
          { title: 'EOD (End of Day)', value: 'eod' },
          { title: 'Intraday', value: 'intraday' },
          { title: 'Trailing', value: 'trailing' },
          { title: 'Static', value: 'static' },
          { title: 'EOD (Capitalised)', value: 'EOD' },
          { title: 'Trailing Intraday', value: 'Trailing Intraday' },
        ],
        layout: 'radio',
      },
    }),
    defineField({ name: 'drawdownAmount',   title: 'Max Drawdown ($)',         type: 'number', group: 'rules' }),
    defineField({ name: 'dailyLossLimit',   title: 'Daily Loss Limit ($)',     type: 'number', group: 'rules' }),
    defineField({ name: 'profitTarget',     title: 'Profit Target ($)',        type: 'number', group: 'rules' }),
    defineField({ name: 'profitSplit',      title: 'Profit Split (%)',         type: 'number', group: 'rules', validation: (r) => r.min(0).max(100) }),
    defineField({ name: 'maxFundedAccounts',title: 'Max Funded Accounts',     type: 'number', group: 'rules' }),
    defineField({ name: 'maxContracts',     title: 'Max Contracts',           type: 'number', group: 'rules' }),
    defineField({ name: 'minTradingDays',   title: 'Min Trading Days to Pass',type: 'number', group: 'rules' }),
    defineField({ name: 'consistencyEval',  title: 'Consistency Rule \u2014 Eval (%)',   type: 'number', group: 'rules', validation: (r) => r.min(0).max(100) }),
    defineField({ name: 'consistencyFunded',title: 'Consistency Rule \u2014 Funded (%)', type: 'number', group: 'rules', validation: (r) => r.min(0).max(100) }),
    defineField({
      name: 'payoutFrequency',
      title: 'Payout Frequency',
      type: 'string',
      group: 'rules',
      options: {
        list: [
          { title: 'Weekly',    value: 'weekly' },
          { title: 'Bi-Weekly', value: 'biweekly' },
          { title: 'Monthly',   value: 'monthly' },
          { title: 'On Demand', value: 'on_demand' },
        ],
        layout: 'radio',
      },
    }),
    defineField({ name: 'retailEvalFee',     title: 'Retail Eval Fee ($)',      type: 'number', group: 'pricing' }),
    defineField({ name: 'evalFee',           title: 'Eval Fee ($)',             type: 'number', group: 'pricing', validation: (r) => r.required().min(0) }),
    defineField({ name: 'activationFee',     title: 'Activation Fee ($)',       type: 'number', group: 'pricing', initialValue: 0 }),
    defineField({ name: 'monthlyFee',        title: 'Monthly Fee ($)',          type: 'number', group: 'pricing', initialValue: 0 }),
    defineField({ name: 'activeDiscountPct', title: 'Active Discount (%)',      type: 'number', group: 'pricing', initialValue: 0, validation: (r) => r.min(0).max(100) }),
    defineField({ name: 'hasDiscount',       title: 'Has Active Discount',      type: 'boolean', group: 'pricing', initialValue: false }),
    defineField({
      name: 'discountAppliesToEvalOnly',
      title: 'Discount applies to Eval fee only (NexGen-style)',
      description: 'ON: discount hits the eval fee only; activation is paid in full on top. OFF: standard (discount applies to eval + activation together). Drives the Total Cost formula below.',
      type: 'boolean',
      group: 'pricing',
      initialValue: false,
    }),
    defineField({
      name: 'baseCostToFunded',
      title: 'Base Cost to Funded ($)',
      description: 'Auto-calculated, read-only. Pre-discount cost: eval + activation (or eval only when One-Time).',
      type: 'number',
      group: 'pricing',
      components: { input: ComputedCostInput },
    }),
    defineField({
      name: 'totalCostToFunded',
      title: 'Total Cost to Funded ($)',
      description: 'Auto-calculated, read-only. Standard: (eval+activation)\u00d7(1\u2212disc). NexGen (toggle above): (eval\u00d7(1\u2212disc))+activation. Instant (One-Time): eval only.',
      type: 'number',
      group: 'pricing',
      validation: (r) => r.required().min(0),
      components: { input: ComputedCostInput },
    }),
    defineField({ name: 'priceVerified', title: 'Price Verified', type: 'boolean', group: 'meta', initialValue: true }),
    defineField({
      name: 'priceStatus',
      title: 'Price Status',
      type: 'string',
      group: 'meta',
      options: {
        list: [
          { title: 'OK',           value: 'ok' },
          { title: 'Needs Review', value: 'needs_review' },
          { title: 'Outdated',     value: 'outdated' },
        ],
        layout: 'radio',
      },
      initialValue: 'ok',
    }),
    defineField({ name: 'notes', title: 'Internal Notes', type: 'text', rows: 3, group: 'meta' }),
  ],
  preview: {
    select: { title: 'planLabel', subtitle: 'firm.name', discount: 'activeDiscountPct' },
    prepare({ title, subtitle, discount }: any) {
      return { title, subtitle: subtitle + (discount ? ' \u00b7 ' + discount + '% off' : '') }
    },
  },
})
